resources:

  - namespace.yaml

  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml

  - ingress.yaml