apiVersion: v1
kind: Secret

metadata:
  name: phoenix-secret
  namespace: phoenix

type: Opaque

stringData:
  # PostgreSQL
  DB_USERNAME: "postgres"
  DB_PASSWORD: "DxSQNLVIt/6qMHRlxWavjPH4PeRTVh3G"

  # Flask
  SECRET_KEY: "aa151c542cc6f6890d65bd4a290ab73647c4a2071795c7636f5c1fcda3c0d6ba"

  # JWT
  JWT_SECRET_KEY: "0b629ffb9e29e77a12612186ea269ff6837ee9408da2c93f5208bfd42f4292f2"

  # Database URL
  DATABASE_URL: "postgresql://postgres:DxSQNLVIt/6qMHRlxWavjPH4PeRTVh3G@postgres:5432/phoenix"