[server]
control-plane ansible_host=3.238.194.251 private_ip=10.0.1.120

[agents]
worker-1 ansible_host=52.90.14.136 private_ip=10.0.2.57
worker-2 ansible_host=100.53.6.21 private_ip=10.0.3.100

[k3s_cluster:children]
server
agents

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/mkaey/.ssh/capstone-key.pem
ansible_python_interpreter=/usr/bin/python3
