[server]
control-plane ansible_host=100.54.230.114 private_ip=10.0.1.177

[agents]
worker-1 ansible_host=54.92.209.187 private_ip=10.0.2.116
worker-2 ansible_host=13.221.81.201 private_ip=10.0.3.174

[k3s_cluster:children]
server
agents

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/mkaey/.ssh/capstone-key.pem
ansible_python_interpreter=/usr/bin/python3
