[server]
control-plane ansible_host=100.58.189.139 private_ip=10.0.1.213

[agents]
worker-1 ansible_host=18.207.222.34 private_ip=10.0.2.147
worker-2 ansible_host=54.167.87.44 private_ip=10.0.3.199

[k3s_cluster:children]
server
agents

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/mkaey/.ssh/capstone-key.pem
ansible_python_interpreter=/usr/bin/python3
